version: '3.4'

services:
  ipxe:
    image: ipxe
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/bash -c "make bin/ipxe.iso DEBUG=malloc EMBED=test.ipxe"
    volumes:
      - ./src:/usr/src/ipxe
