version: '3.4'

services:
  ipxe:
    image: ipxe
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/bash -c "make bin-x86_64-efi/snponly.efi"
    volumes:
      - ./src:/usr/src/ipxe
